# https://aka.ms/yaml

trigger:
- master

stages:
- stage: amd64
  displayName: amd64 (Intel/AMD64)
  dependsOn: [] 
  variables:
    - name: ARCH
      value: amd64 
  jobs:
  - job: 
    displayName: build and push image
    timeoutInMinutes: 60
    pool:
        vmImage: 'ubuntu-latest'
    steps:
        - script: |
            make qemu
            make wrap-$(ARCH)
          displayName: setup
        - task: Docker@2
          displayName: login to Docker Hub
          inputs:
            command: login
            containerRegistry: insightfulbuildbot
        - script: |
            make build-$(ARCH)
          displayName: build $(ARCH)
        - script: |
            make push-$(ARCH)
          displayName: push image for $(ARCH)


- stage: arm32v7
  displayName: arm32v7 (Pi 2+ and other armhf)
  dependsOn: []
  variables:
    - name: ARCH
      value: arm32v7 
  jobs:
  - job: 
    displayName: build and push image
    timeoutInMinutes: 320
    pool:
        vmImage: 'ubuntu-latest'
    steps:
        - script: |
            make qemu
            make wrap-$(ARCH)
          displayName: setup
        - task: Docker@2
          displayName: login to Docker Hub
          inputs:
            command: login
            containerRegistry: insightfulbuildbot
        - script: |
            make build-$(ARCH)
          displayName: build $(ARCH)
        - script: |
            make push-$(ARCH)
          displayName: push image for $(ARCH)

- stage: arm64v8
  displayName: arm64v8 (Pi 3+ and other ARM64)
  dependsOn: []
  variables:
    - name: ARCH
      value: arm64v8
  jobs:
  - job: 
    displayName: build and push image
    timeoutInMinutes: 320
    pool:
        vmImage: 'ubuntu-latest'
    steps:
        - script: |
            make qemu
            make wrap-$(ARCH)
          displayName: setup
        - task: Docker@2
          displayName: login to Docker Hub
          inputs:
            command: login
            containerRegistry: insightfulbuildbot
        - script: |
            make build-$(ARCH)
          displayName: build $(ARCH)
        - script: |
            make push-$(ARCH)
          displayName: push image for $(ARCH)

- stage: arm32v6
  displayName: arm32v6 (Pi A/B/Zero)
  dependsOn: []
  variables:
    - name: ARCH
      value: arm32v6
  jobs:
  - job: 
    displayName: build and push image
    timeoutInMinutes: 320
    pool:
        vmImage: 'ubuntu-latest'
    steps:
        - script: |
            make qemu
            make wrap-$(ARCH)
          displayName: setup
        - task: Docker@2
          displayName: login to Docker Hub
          inputs:
            command: login
            containerRegistry: insightfulbuildbot
        - script: |
            make build-$(ARCH)
          displayName: build $(ARCH)
        - script: |
            make push-$(ARCH)
          displayName: push image for $(ARCH)

- stage: manifest
  displayName: multi-arch manifest
  dependsOn: 
    - amd64
    - arm32v7
    - arm32v6
    - arm64v8
  jobs:
  - job: Manifest 
    pool:
      vmImage: 'ubuntu-latest'
    steps:
        - script: |
            make setup-manifest
            docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
            make build-manifest
            make push-manifest