# https://aka.ms/yaml

trigger:
- master

stages:
- stage: amd64
  displayName: Build for amd64
  variables:
    - name: ARCH
      value: amd64 
  jobs:
  - job: setup
    pool:
        vmImage: 'ubuntu-latest'
    steps:
        - script: |
            echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
            mkdir -p $HOME/.docker && echo '{"experimental":"enabled"}' | tee $HOME/.docker/config.json
            sudo service docker restart
            make qemu
            make wrap-$(ARCH)
  - job: build
    pool:
        vmImage: 'ubuntu-latest'
    dependsOn: setup
    steps:
        - script: |
            make build-$(ARCH)
  - job: push
    pool:
        vmImage: 'ubuntu-latest'
    dependsOn: build
    steps:
        - script: |
            make push-$(ARCH)


- stage: arm32v7
  displayName: Build for arm32v7
  variables:
    - name: ARCH
      value: arm32v7 
  jobs:
  - job: setup
    pool:
      vmImage: 'ubuntu-latest'  
    steps:
        - script: |
            echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
            mkdir -p $HOME/.docker && echo '{"experimental":"enabled"}' | tee $HOME/.docker/config.json
            sudo service docker restart
            make qemu
            make wrap-$(ARCH)
  - job: build
    dependsOn: setup
    pool:
      vmImage: 'ubuntu-latest'  
    steps:
        - script: |
            make build-$(ARCH)
  - job: push
    dependsOn: build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
        - script: |
            make push-$(ARCH)

- stage: arm32v6
  displayName: Build for arm32v6
  variables:
    - name: ARCH
      value: arm32v6
  jobs:
  - job: setup
    pool:
      vmImage: 'ubuntu-latest'
    steps:
        - script: |
            echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
            mkdir -p $HOME/.docker && echo '{"experimental":"enabled"}' | tee $HOME/.docker/config.json
            sudo service docker restart
            make qemu
            make wrap-$(ARCH)
  - job: build
    dependsOn: setup
    pool:
      vmImage: 'ubuntu-latest'
    steps:
        - script: |
            make build-$(ARCH)
  - job: push
    dependsOn: build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
        - script: |
            make push-$(ARCH)

- stage: manifest
  displayName: Build multi-arch manifest
  dependsOn: 
    - amd64
    - arm32v7
    - arm32v6
  jobs:
  - job: setup
    pool:
      vmImage: 'ubuntu-latest'
    steps:
        - script: |
            echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
            mkdir -p $HOME/.docker && echo '{"experimental":"enabled"}' | tee $HOME/.docker/config.json
            sudo service docker restart
  - job: manifest
    dependsOn: setup
    pool:
      vmImage: 'ubuntu-latest'
    steps:
        - script: |
            make manifest