# https://aka.ms/yaml

trigger:
- master

stages:
- stage: amd64
  displayName: amd64 (Intel/AMD64)
  dependsOn: [] 
  variables:
    - name: ARCH
      value: amd64 
  jobs:
  - job: 
    displayName: build and push image
    timeoutInMinutes: 120
    pool:
        vmImage: 'ubuntu-latest'
    steps:
        - script: |
            echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
            mkdir -p $HOME/.docker && echo '{"experimental":"enabled"}' | tee $HOME/.docker/config.json
            sudo service docker restart
            make qemu
            make wrap-$(ARCH)
          displayName: setup
        - task: Docker@2
          displayName: login to Docker Hub
          inputs:
            command: login
            containerRegistry: insightfulbuildbot
        - script: |
            make build-$(ARCH)
          displayName: build $(ARCH)
        - script: |
            make push-$(ARCH)
          displayName: push image for $(ARCH)


- stage: arm32v7
  displayName: arm32v7 (Raspberry Pi 2+ and other armhf)
  dependsOn: []
  variables:
    - name: ARCH
      value: arm32v7 
  jobs:
  - job: 
    displayName: build and push image
    timeoutInMinutes: 240
    pool:
        vmImage: 'ubuntu-latest'
    steps:
        - script: |
            echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
            mkdir -p $HOME/.docker && echo '{"experimental":"enabled"}' | tee $HOME/.docker/config.json
            sudo service docker restart
            make qemu
            make wrap-$(ARCH)
          displayName: setup
        - task: Docker@2
          displayName: login to Docker Hub
          inputs:
            command: login
            containerRegistry: insightfulbuildbot
        - script: |
            make build-$(ARCH)
          displayName: build $(ARCH)
        - script: |
            make push-$(ARCH)
          displayName: push image for $(ARCH)

- stage: arm32v6
  displayName: arm32v6 (Raspberry Pi A/B/Zero)
  dependsOn: []
  variables:
    - name: ARCH
      value: arm32v6
  jobs:
  - job: 
    displayName: build and push image
    timeoutInMinutes: 240
    pool:
        vmImage: 'ubuntu-latest'
    steps:
        - script: |
            echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
            mkdir -p $HOME/.docker && echo '{"experimental":"enabled"}' | tee $HOME/.docker/config.json
            sudo service docker restart
            make qemu
            make wrap-$(ARCH)
          displayName: setup
        - task: Docker@2
          displayName: login to Docker Hub
          inputs:
            command: login
            containerRegistry: insightfulbuildbot
        - script: |
            make build-$(ARCH)
          displayName: build $(ARCH)
        - script: |
            make push-$(ARCH)
          displayName: push image for $(ARCH)

- stage: manifest
  displayName: multi-arch manifest
  dependsOn: 
    - amd64
    - arm32v7
    - arm32v6
  jobs:
  - job: 
    pool:
      vmImage: 'ubuntu-latest'
    steps:
        - script: |
            echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
            mkdir -p $HOME/.docker && echo '{"experimental":"enabled"}' | tee $HOME/.docker/config.json
            sudo service docker restart
          displayName: setup
        - task: Docker@2
          displayName: login to Docker Hub
          inputs:
            command: login
            containerRegistry: insightfulbuildbot
        - script: |
            make manifest
          displayName: push manifest