# https://aka.ms/yaml

trigger:
- master

stages:
- stage: amd64
  displayName: amd64 (Intel/AMD)
  dependsOn: [] 
  jobs:
  - template: .azure-pipelines-job.yml 
    parameters:
      arch: amd64
      timeout: 120

- stage: arm32v6
  displayName: arm32v6 (Pi B+/Zero+)
  dependsOn: []
  jobs:
  - template: .azure-pipelines-job.yml
    parameters:
      arch: arm32v6
      timeout: 320

- stage: arm32v7
  displayName: arm32v7 (Pi 2+ and other armhf)
  dependsOn: []
  jobs:
  - template: .azure-pipelines-job.yml
    parameters:
      arch: arm32v7
      timeout: 320

- stage: arm64v8
  displayName: arm64v8 (Pi 3+/4 and other ARM64)
  dependsOn: []
  jobs:
  - template: .azure-pipelines-job.yml
    parameters:
      arch: arm64v8
      timeout: 320

- stage: Manifest
  displayName: multi-arch manifest
  dependsOn: 
    - amd64
    - arm32v6
    - arm32v7
    - arm64v8
  jobs:
  - job: Manifest 
    pool:
      vmImage: 'ubuntu-latest'
    steps:
        - script: |
            rm -rf ~/.docker
            docker -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD) login docker.io
            make manifest
